repos:
- repo: local
  hooks:
    - id: fmt
      name: fmt
      language: system
      entry: make
      args: ["fmt"]
      pass_filenames: false
    - id: vet
      name: vet
      language: system
      entry: make
      args: ['vet']
      pass_filenames: false

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
    - id: fix-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
      exclude: ^vendor
    - id: check-shebang-scripts-are-executable
      exclude: ^vendor
    - id: check-merge-conflict
    - id: check-symlinks
    - id: destroyed-symlinks
    - id: check-yaml
      args: [-m]
    - id: check-json
    - id: detect-private-key
    - id: end-of-file-fixer
      exclude: ^vendor
    - id: no-commit-to-branch
    - id: trailing-whitespace
      exclude: ^vendor

- repo: https://github.com/openstack/bashate.git
  rev: 2.1.1
  hooks:
    - id: bashate
      entry: bashate --error . --ignore=E006,E040,E011,E020,E012
